@component('mail::layout')
    {{-- Header --}}
    @slot('header')
        @component('mail::header', ['url' => config('app.url')])
            Order Confirmation
        @endcomponent
    @endslot

    {{-- Body --}}
    New Issue has been created ! <br>
    <h1>Project Name: {{$messages[1]}} </h1> <br>
    <h4>Issue Name: {{$messages[0]}} </h4>
    <h4>Severity: {{$messages[5]}} </h4>
    <h4>Reporter: {{$messages[2]}} </h4>
    <h4>Created: {{$messages[3]}} </h4>
    <h4>Status: {{$messages[4]}} </h4>
    {{-- Subcopy </h4> --}}
    @isset($messages)
        @slot('subcopy')
            @component('mail::subcopy')
                This email is auto generated by Bug Report Application.
            @endcomponent
        @endslot
    @endisset
    {{-- Subcopy --}}
    @component('mail::button', ['url' => $url, 'color' => 'green'])
        View Details
    @endcomponent

    {{-- Footer --}}
    @slot('footer')
        @component('mail::footer')
            © {{ date('Y') }} {{ config('app.name') }}. All rights reserved!
        @endcomponent
    @endslot
@endcomponent
